setwd("~/")
 library(readxl)
 book1 <- read.csv("BOOK1.csv")
 View(book1)
 summary(book1)
 # summary of the dataset which is created by myself.
  install.packages("vcd")
  mean(book1$AGE)
   median(book1$AGE)
   mode(book1$AGE)
   install.packages("dplyr")
    library(dplyr)
    select(book1, AGE:SERIES)
     filter(book1, AGE==21)
     filter(book1, SERIES==5)
     arrange(book1, GENDER)
     plot(book1$AGE,book1$SERIES)
     plot(book1$AGE,book1$COMPLAINTS)
    